@startuml point
start
:get userBalance;
if (None || len == 0) then (YES)
  :throw error;
  :return;
else (NO)
  if (userBalance == 0) then (YES)
    :return (0, 0);
  else (NO)
    :get payAmount;
    if (None || len == 0) then (YES)
      :throw error;
    else (NO)
      if (payAmount==0) then
        :return (0, 0);
      else (NO)
        :get everyPoints;
        if(None || len == 0) then (YES)
          :throw error;
        else (NO)
          :get type;
          if(None || len == 0) then (YES)
            :throw error;
          else (NO)
            :payPoints = payAmount * everyPoints;
            if (type === whole) then (YES)
              :result === getWholePoint;
              :result;
            else (NO)
              :get startPoint;
              if (None || len == 0) then (YES)
                :throw error;
              else (NO)
                :get maxMultiple;
                if (None || len == 0) then (YES)
                  :throw error;
                else (NO)
                  if (type === multiple) then (YES)
                    :result = getmultiplePoint;
                    :result;
                  else (NO)
                    :result === getRadomPoints;
                    :result;
                  endif
                endif
              endif
            endif
          endif
        endif
      endif
    endif
  endif
endif
stop
@enduml