@startuml referral

start
:前端拿到后台的短链接并把链接塞进二维码;
:扫码进入App;
fork
  :tab;
  if(登录) then (yes)
    stop
  else (no)
    :记录保存'true',并永远不会删除这个记录;
  endif
fork again
  :referral;
  :解析并拿到长链接;
end fork
if(拿到了tab的记录和链接) then (yes)
  :在长链接中拿到referralId;
  :跳转到注册登录页面并附带referralId;
  stop
else (no)  
  stop
  @enduml
