@startuml

start
:前端拿到后台的短链接并把链接塞进二维码;
if (扫码进入App) then (tab)
  if(登录) then (yes)
    :return;
  stop
  else (no)  
    fork
      :后台;
      :记录保存'true',并永远不会删除这个记录;
    fork again
      :前台;
      :因为已经后台进入过,也会拿到'true',因为记录没删;
    end fork
  endif  
else (referral)
  :解析并拿到长链接;
endif
  #palegreen:如果拿到到了tab的记录和链接;
:在长链接中拿到referralId;
:跳转到注册登录页面并附带referralId;
stop
@enduml
